# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsrecord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='userID',
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Users'),
        ),
    ]
