# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsrecord', '0002_auto_20171206_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreport',
            name='stressLevel',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 262423, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 262538, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 260544, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 260589, tzinfo=utc), null=True),
        ),
    ]
