# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsrecord', '0003_auto_20171208_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreport',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 6, 50, 91262, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 6, 50, 91305, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 6, 50, 89780, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 6, 50, 89827, tzinfo=utc), null=True),
        ),
    ]
