# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsrecord', '0004_auto_20171208_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreport',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 537407, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 537450, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 535894, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 535944, tzinfo=utc), null=True),
        ),
    ]
