# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsrecord', '0006_auto_20171208_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreport',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitalreport',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
