# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0014_auto_20180102_0544'),
        ('doctor', '0002_doctorappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dose', models.CharField(choices=[('One', 'One'), ('Two', 'Two')], max_length=100)),
                ('medicine_pic', models.ImageField(upload_to='')),
                ('schedule', models.CharField(choices=[('Morning', 'Morning'), ('AfterNoon', 'AfterNoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=100)),
                ('medicine_type', models.CharField(choices=[('Everyday', 'Everyday'), ('Hourly', 'Hourly'), ('Weekly', 'Weekly')], max_length=100)),
                ('instructions', models.CharField(max_length=1000)),
                ('remind_me', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], max_length=100)),
                ('refills', models.CharField(max_length=100)),
                ('boxters', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Users')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor')),
            ],
        ),
    ]
