# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20180117_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicine_pic',
            field=models.ImageField(upload_to='/home/pranav/apis-django/doctorlog/media'),
        ),
    ]
