# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0003_auto_20171206_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaTitle', models.CharField(max_length=1000)),
                ('mediaURL', models.URLField(blank=True, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('location', models.TextField()),
                ('length', models.TextField()),
                ('triggeredBy', models.TextField()),
                ('otherSymptoms', models.TextField()),
                ('reliefBy', models.TextField()),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportedDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaURL', models.URLField(blank=True, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('length', models.TextField(blank=True, null=True)),
                ('triggeredBy', models.TextField(blank=True, null=True)),
                ('otherSymptoms', models.TextField(blank=True, null=True)),
                ('reliefBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_user', to='modules.Users')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='symptomsrecord',
            name='symptomsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_users', to='symptomsrecord.SymptomsUser'),
        ),
        migrations.AddField(
            model_name='symptomsrecord',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_report_user', to='modules.Users'),
        ),
    ]
