# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symptomsrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsdef',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 256483, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='describe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 256529, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsrecord',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='symptomsrecord',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 259012, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 257797, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 6, 5, 53, 257841, tzinfo=utc), null=True),
        ),
    ]
