# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symptomsrecord', '0003_auto_20171208_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsdef',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 531807, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 531858, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsrecord',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 534382, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 533137, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 7, 39, 3, 533185, tzinfo=utc), null=True),
        ),
    ]
