# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('symptomsrecord', '0004_auto_20171208_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsdef',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 17, 705467, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 17, 705517, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsrecord',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 17, 708072, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='createdDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 17, 706815, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='updatedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 8, 8, 0, 17, 706861, tzinfo=utc), null=True),
        ),
    ]
