# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptomsrecord', '0006_auto_20171215_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomsdef',
            name='videoTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='symptomsdef',
            name='videoURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomsuser',
            name='videoTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='symptomsuser',
            name='videoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
