# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptomsrecord', '0007_auto_20180118_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsdef',
            name='describe',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='length',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='location',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='mediaURL',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='otherSymptoms',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='reliefBy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='triggeredBy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='videoURL',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='describe',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='length',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='location',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='mediaURL',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='otherSymptoms',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='reliefBy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='triggeredBy',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsuser',
            name='videoURL',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
