# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaTitle', models.CharField(max_length=1000)),
                ('mediaURL', models.URLField()),
                ('describe', models.TextField()),
                ('location', models.TextField()),
                ('length', models.TextField()),
                ('triggeredBy', models.TextField()),
                ('otherSymptoms', models.TextField()),
                ('reliefBy', models.TextField()),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportedDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('mediaTitle', models.CharField(max_length=1000)),
                ('mediaURL', models.URLField(blank=True, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('length', models.TextField(blank=True, null=True)),
                ('triggeredBy', models.TextField(blank=True, null=True)),
                ('otherSymptoms', models.TextField(blank=True, null=True)),
                ('reliefBy', models.TextField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('User', 'User')], max_length=50)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='VitalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('systol', models.CharField(max_length=100)),
                ('dystol', models.CharField(max_length=100)),
                ('heartRate', models.CharField(max_length=10)),
                ('options', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=10)),
                ('pulse', models.CharField(max_length=10)),
                ('sugar', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=1000)),
                ('reportedDate', models.DateTimeField()),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('mediaURL', models.URLField()),
                ('mediaTitle', models.CharField(max_length=1000)),
                ('options', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('tips', models.CharField(max_length=1000)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vitalreport',
            name='vitalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Vitals'),
        ),
        migrations.AddField(
            model_name='symptomsuser',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Users'),
        ),
        migrations.AddField(
            model_name='symptomsrecord',
            name='symptomsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.SymptomsUser'),
        ),
        migrations.AddField(
            model_name='symptomsrecord',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Users'),
        ),
    ]
