# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsdef',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptomsdef',
            name='mediaURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='mediaTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='mediaURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
