# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20171206_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomsuser',
            name='mediaTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
