# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20171206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
