# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 04:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0011_auto_20171208_1333'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstName',
            field=models.CharField(error_messages={'unique': 'Please provide a first name.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastName',
            field=models.CharField(error_messages={'unique': 'Please provide a last name.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('User', 'User')], default='User', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
