# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_auto_20171215_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='users',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastName',
        ),
    ]
