# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_auto_20171215_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
