# Generated by Django 2.0 on 2017-12-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('time_to_read', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'article categories',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('friendly_description', models.TextField()),
                ('function', models.CharField(max_length=255)),
                ('video_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedCategorizedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ArticleCategory')),
            ],
        ),
        migrations.AddField(
            model_name='dosage',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosages', to='api.Medication'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='articles',
            field=models.ManyToManyField(through='api.OrderedCategorizedArticle', to='api.Article'),
        ),
    ]
