# Generated by Django 2.0 on 2017-12-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedcategorizedarticle',
            unique_together={('article', 'category')},
        ),
    ]
