# Generated by Django 2.0 on 2017-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20171211_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(default='https://d1c9s9ipqrs724.cloudfront.net/images/article-image-placeholder.png',
                                  max_length=255),
            preserve_default=False,
        ),
    ]
