# Generated by Django 2.0 on 2018-01-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
