# Generated by Django 2.0 on 2018-01-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180105_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='instructions',
            field=models.TextField(default='Instructions go here.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='interactions',
            field=models.TextField(default='Interactions go here'),
            preserve_default=False,
        ),
    ]
