# Generated by Django 2.0 on 2018-01-18 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(default='Description goes here.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='image_title',
            field=models.CharField(default='Image title goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='length',
            field=models.CharField(default='Length goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='location',
            field=models.CharField(default='Location goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='other_symptoms',
            field=models.TextField(default='Other symptoms go here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='relief_by',
            field=models.TextField(default='Relief by goes here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='subtitle',
            field=models.CharField(default='Subtitle goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='triggered_by',
            field=models.TextField(default='Triggered by goes here.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
