# Generated by Django 2.0 on 2018-01-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auto_20180118_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDevice',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('device_identifier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Medication')),
                ('patient_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PatientDevice')),
            ],
        ),
    ]
