# Generated by Django 2.0 on 2018-01-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180125_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='instructions',
            new_name='information',
        ),
    ]
