# Generated by Django 2.0 on 2018-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180127_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_title', models.CharField(max_length=1000)),
                ('options', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('tips', models.CharField(max_length=1000)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
