# Generated by Django 2.0 on 2018-01-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180130_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitals',
            new_name='Vital',
        ),
    ]
