# Generated by Django 2.0 on 2018-01-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180130_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='media_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
