# Generated by Django 2.0 on 2018-01-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180130_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedsymptom',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='loggedsymptom',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='vital',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='vital',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
